lista = [29,23,15,17]
lista .sort(reverse=True)
print(lista)
maiorElemento = max(lista)
print("maior elemento da lista : ", maiorElemento)  
lista.append(17)
menorElemento = min(lista)
print("menor elemento da lista: ",menorElemento)
print("lista final",lista)
print("item",lista[2])